### ISSUE TITLE
Dropping Python 2.7 and 3.4 support

### ISSUE THREAD

**Issue by MuellerSeb** [GeoStat-Framework/pentapy#6]
Since Python 2 will reach it's EOL on [**1. Jan 2020**](https://www.python.org/doc/sunset-python-2/), we will drop support for it.
Python 3.4 has already reached its EOL on 2019-03-18, so we are dropping support here, too.

The next minor release (v1.1) will then be **Python 3 only**.

Since TravisCI supports Windows but only for Python 3 we can then drop the use of Appveyor and stick to one CI system.

**Comment by hugovk** [comment]
See also "NEP 29 — Recommend Python and Numpy version support as a community policy standard":

* https://numpy.org/neps/nep-0029-deprecation_policy.html

**Comment by MuellerSeb** [comment]
Done with https://github.com/GeoStat-Framework/pentapy/pull/10
